### PR TITLE
Update for CUDA 12.4.0

### PR DESCRIPTION
**Pull request by adibbley**
xref: https://github.com/conda-forge/cuda-feedstock/issues/17

### CODE REVIEW

**Comment by adibbley** [comment]
@conda-forge-admin, please restart ci

**Comment by jakirkham** [comment]
Missing `libcusolver` builds on `linux_aarch64` and `linux_ppc64le` due to a known Travis CI issue under investigation. More details in comment: https://github.com/conda-forge/libcusolver-feedstock/pull/13#issuecomment-1981805589

Have already started `libcusolver` builds on Travis CI. So these should be out in a bit. Let's keep an eye on those builds (linked the comment referenced above)

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin, please restart CI

**Comment by jakirkham** [comment]
For all the `cuda-libraries*` feedstocks, at least one Travis CI build queued for ~6hrs and then was marked as errored. AFAICT the job never ran. Restarted after. Then it ran and passed in short order

Think the queue may just be getting overloaded (hence the need to wait for things to quiet down and restart to get builds through)

**Pull request merged**
